#lab17
dbGetQuery(PSTAT10db, 'SELECT * FROM INVOICES INNER JOIN STOCK_TOTAL 
           WHERE INVOICES.PROD_NO = STOCK_TOTAL.PROD_NO')

STOCK_TOTAL
INVOICES
#2
PRODUCT
CUSTOMER
SALES_ORDER
SALES_ORDER_LINE

dbGetQuery(PSTAT10db, 'SELECT DISTINCT P.NAME, P.COLOR FROM PRODUCT P, CUSTOMER C, SALES_ORDER S, SALES_ORDER_LINE O
           WHERE C.CUST_NO = S.CUST_NO
           AND S.ORDER_NO = O.ORDER_NO
           AND O.PROD_NO = P.PROD_NO
           AND C.NAME = "ALEX" OR C.NAME = "CAROL"')
#3
dbGetQuery(PSTAT10db, 'SELECT * FROM PRODUCT WHERE PROD_NO = "p1"')

#4
dbGetQuery(PSTAT10db, 'SELECT DEPARTMENT.DEPT_NO FROM DEPARTMENT, EMPLOYEE
           WHERE EMPLOYEE.DEPT_NO = DEPARTMENT.DEPT_NO
           AND EMPLOYEE.NI_NO = "123"')
dbGetQuery(PSTAT10db, 'SELECT DEPT_NO FROM DEPARTMENT 
           WHERE DEPT_NO = (SELECT DEPT_NO FROM EMPLOYEE WHERE NI_NO = "123" )')


#5
dbGetQuery(PSTAT10db, 'SELECT DEPT_NO FROM DEPARTMENT WHERE NAME = "Accounts"')

#6
dbGetQuery(PSTAT10db, 'SELECT NAME FROM DEPARTMENT WHERE NAME != "Stores"')
