SALES_ORDER <- read.csv("~/Desktop/PSTAT10/SALES_ORDER.txt")
SALES_ORDER_LINE <- read.csv("~/Desktop/PSTAT10/SALES_ORDER_LINE.txt")
INVOICES <- read.csv("~/Desktop/PSTAT10/INVOICES.txt")
EMPLYEE_PHONE<-read.csv("~/Desktop/PSTAT10/EMPLOYEE_PHONE.txt")
DEPARTMENT <- read.csv("~/Desktop/PSTAT10/DEPARTMENT.txt")
STOCK_TOTAL <- read.csv("~/Desktop/PSTAT10/STOCK_TOTAL.txt")
CUSTOMER <- read.csv("~/Desktop/PSTAT10/CUSTOMER.txt")
EMPLOYEE<-read.csv("~/Desktop/PSTAT10/EMPLOYEE.txt")


PSTAT10db<-dbConnect(RSQLite::SQLite(), "PSTAT10-db,sqlite")


dbWriteTable(PSTAT10db,"SALES_ORDER",SALES_ORDER)
dbWriteTable(PSTAT10db,"SALES_ORDER_LINE",SALES_ORDER_LINE)
dbWriteTable(PSTAT10db,"INVOICES",INVOICES)
dbWriteTable(PSTAT10db,"EMPLYEE_PHONE",EMPLYEE_PHONE)
dbWriteTable(PSTAT10db,"DEPARTMENT",DEPARTMENT)
dbWriteTable(PSTAT10db,"STOCK_TOTAL",STOCK_TOTAL)
dbWriteTable(PSTAT10db,"CUSTOMER",CUSTOMER)
dbWriteTable(PSTAT10db,"EMPLOYEE",EMPLOYEE)

dbListTables(PSTAT10db)

dbGetQuery(PSTAT10db,'SELECT * FROM EMPLOYEE')
dbGetQuery(PSTAT10db,'SELECT DISTINCT NAME FROM EMPLOYEE')
dbGetQuery(PSTAT10db,'SELECT * FROM EMPLOYEE WHERE AGE>30')
