dbGetQuery(PSTAT10db, 'SELECT EMPLOYEE.EMP_NO, EMPLOYEE.NAME, DEPARTMENT.NAME 
           FROM EMPLOYEE INNER JOIN DEPARTMENT')

dbGetQuery(PSTAT10db, 'SELECT EMP_NO, EMPLOYEE.NAME, DEPARTMENT.NAME 
           FROM EMPLOYEE INNER JOIN DEPARTMENT
           ')

PRODUCT
CUSTOMER

dbGetQuery(PSTAT10db,'SELECT NAME AND COLOR 
           FROM PRODUCT
           ORDER BY')
PRODUCT
CUSTOMER
SALES_ORDER
SALES_ORDER_LINE

dbGetQuery(PSTAT10db,'SELECT DISTINCT C.NAME, P.NAME AS ProductName, COLOR AS RequiredColor
           FROM CUSTOMER C, SALES_ORDER_LINE O, SALES_ORDER S, PRODUCT P
           WHERE C.CUST_NO = S.CUST_NO
           AND S.ORDER_NO = O.ORDER_NO
           AND O.PROD_NO = P.PROD_NO
           AND C.NAME = "ALEX" ')
